services:
  backend:
    image: alpine:latest
    container_name: pocketbase_server
    restart: always
    ports:
      - "1234:8090"
    volumes:
      - ./pb_data:/pb_data
    command: >
      /bin/sh -c "apk add --no-cache unzip ca-certificates wget &&
      wget -O /tmp/pb.zip https://github.com/pocketbase/pocketbase/releases/download/v0.22.3/pocketbase_0.22.3_linux_arm64.zip &&
      unzip -o /tmp/pb.zip -d /usr/local/bin/ &&
      chmod +x /usr/local/bin/pocketbase &&
      /usr/local/bin/pocketbase serve --http=0.0.0.0:8090 --dir=/pb_data"
  tunnel:
      image: cloudflare/cloudflared:latest
      container_name: cloudflared-tunnel
      restart: unless-stopped
      command: tunnel run
      environment:
        - TUNNEL_TOKEN=ADD YOUR TOKEN HERE (IF WORKING WITH CLOUDFLARE TUNNELS)
